2021-12-13 19:50:09,513 INFO    MainThread:1188 [wandb_setup.py:_flush():71] setting env: {}
2021-12-13 19:50:09,513 INFO    MainThread:1188 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-13 19:50:09,514 INFO    MainThread:1188 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\Usuario\Desktop\Uni\DataDaniMAPSIV\PSIV\wandb\run-20211213_195009-15zwcew5\logs\debug.log
2021-12-13 19:50:09,514 INFO    MainThread:1188 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\Usuario\Desktop\Uni\DataDaniMAPSIV\PSIV\wandb\run-20211213_195009-15zwcew5\logs\debug-internal.log
2021-12-13 19:50:09,514 INFO    MainThread:1188 [wandb_init.py:init():404] calling init triggers
2021-12-13 19:50:09,514 INFO    MainThread:1188 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-12-13 19:50:09,516 INFO    MainThread:1188 [wandb_init.py:init():449] starting backend
2021-12-13 19:50:09,516 INFO    MainThread:1188 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2021-12-13 19:50:09,520 INFO    MainThread:1188 [backend.py:ensure_launched():199] starting backend process...
2021-12-13 19:50:09,603 INFO    MainThread:1188 [backend.py:ensure_launched():204] started backend process with pid: 5276
2021-12-13 19:50:09,604 INFO    MainThread:1188 [wandb_init.py:init():458] backend started and connected
2021-12-13 19:50:09,605 INFO    MainThread:1188 [wandb_init.py:init():519] updated telemetry
2021-12-13 19:50:09,626 INFO    MainThread:1188 [wandb_init.py:init():549] communicating current version
2021-12-13 19:50:10,190 INFO    MainThread:1188 [wandb_init.py:init():554] got version response 
2021-12-13 19:50:10,190 INFO    MainThread:1188 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-13 19:50:10,431 INFO    MainThread:1188 [wandb_init.py:init():592] starting run threads in backend
2021-12-13 19:50:10,538 INFO    MainThread:1188 [wandb_run.py:_console_start():1816] atexit reg
2021-12-13 19:50:10,539 INFO    MainThread:1188 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2021-12-13 19:50:10,540 INFO    MainThread:1188 [wandb_run.py:_redirect():1727] Wrapping output streams.
2021-12-13 19:50:10,542 INFO    MainThread:1188 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-13 19:50:10,542 INFO    MainThread:1188 [wandb_init.py:init():619] run started, returning control to user process
2021-12-13 19:50:10,543 INFO    MainThread:1188 [wandb_config.py:__setitem__():144] config set learning_rate = 0.001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001BD9B123BB0>>
2021-12-13 19:50:10,543 INFO    MainThread:1188 [wandb_run.py:_config_callback():962] config_cb learning_rate 0.001 None
2021-12-13 19:50:10,544 INFO    MainThread:1188 [wandb_config.py:__setitem__():144] config set batch_size = 32 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001BD9B123BB0>>
2021-12-13 19:50:10,544 INFO    MainThread:1188 [wandb_run.py:_config_callback():962] config_cb batch_size 32 None
2021-12-13 19:50:11,925 INFO    MainThread:1188 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-12-13 19:50:11,925 INFO    MainThread:1188 [wandb_run.py:_restore():1758] restore
2021-12-13 19:50:12,124 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 932
  total_bytes: 932
}

2021-12-13 19:50:12,367 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 932
  total_bytes: 932
}

2021-12-13 19:50:12,476 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 932
  total_bytes: 2881
}

2021-12-13 19:50:12,584 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 932
  total_bytes: 2881
}

2021-12-13 19:50:12,694 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 932
  total_bytes: 2881
}

2021-12-13 19:50:12,803 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2881
  total_bytes: 2881
}

2021-12-13 19:50:12,911 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2881
  total_bytes: 2881
}

2021-12-13 19:50:13,019 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2881
  total_bytes: 2881
}

2021-12-13 19:50:13,127 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2881
  total_bytes: 2881
}

2021-12-13 19:50:13,236 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2881
  total_bytes: 2881
}

2021-12-13 19:50:13,457 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2881
  total_bytes: 2881
}

2021-12-13 19:50:13,963 INFO    MainThread:1188 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2881
  total_bytes: 2881
}
local_info {
}

2021-12-13 19:50:15,042 INFO    MainThread:1188 [wandb_run.py:_append_files():2184] logging synced files
