2021-12-13 20:29:19,759 INFO    MainThread:4200 [wandb_setup.py:_flush():71] setting env: {}
2021-12-13 20:29:19,760 INFO    MainThread:4200 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-13 20:29:19,760 INFO    MainThread:4200 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\Usuario\Desktop\Uni\DataDaniMAPSIV\PSIV\wandb\run-20211213_202919-29708w8n\logs\debug.log
2021-12-13 20:29:19,760 INFO    MainThread:4200 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\Usuario\Desktop\Uni\DataDaniMAPSIV\PSIV\wandb\run-20211213_202919-29708w8n\logs\debug-internal.log
2021-12-13 20:29:19,761 INFO    MainThread:4200 [wandb_init.py:init():404] calling init triggers
2021-12-13 20:29:19,761 INFO    MainThread:4200 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-12-13 20:29:19,761 INFO    MainThread:4200 [wandb_init.py:init():449] starting backend
2021-12-13 20:29:19,761 INFO    MainThread:4200 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2021-12-13 20:29:19,765 INFO    MainThread:4200 [backend.py:ensure_launched():199] starting backend process...
2021-12-13 20:29:19,850 INFO    MainThread:4200 [backend.py:ensure_launched():204] started backend process with pid: 5344
2021-12-13 20:29:19,851 INFO    MainThread:4200 [wandb_init.py:init():458] backend started and connected
2021-12-13 20:29:19,853 INFO    MainThread:4200 [wandb_init.py:init():519] updated telemetry
2021-12-13 20:29:19,876 INFO    MainThread:4200 [wandb_init.py:init():549] communicating current version
2021-12-13 20:29:20,403 INFO    MainThread:4200 [wandb_init.py:init():554] got version response 
2021-12-13 20:29:20,404 INFO    MainThread:4200 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-13 20:29:20,623 INFO    MainThread:4200 [wandb_init.py:init():592] starting run threads in backend
2021-12-13 20:29:20,731 INFO    MainThread:4200 [wandb_run.py:_console_start():1816] atexit reg
2021-12-13 20:29:20,733 INFO    MainThread:4200 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2021-12-13 20:29:20,733 INFO    MainThread:4200 [wandb_run.py:_redirect():1727] Wrapping output streams.
2021-12-13 20:29:20,736 INFO    MainThread:4200 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-13 20:29:20,736 INFO    MainThread:4200 [wandb_init.py:init():619] run started, returning control to user process
2021-12-13 20:29:20,737 INFO    MainThread:4200 [wandb_config.py:__setitem__():144] config set learning_rate = 0.001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002027ACA98B0>>
2021-12-13 20:29:20,737 INFO    MainThread:4200 [wandb_run.py:_config_callback():962] config_cb learning_rate 0.001 None
2021-12-13 20:29:20,737 INFO    MainThread:4200 [wandb_config.py:__setitem__():144] config set batch_size = 32 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002027ACA98B0>>
2021-12-13 20:29:20,737 INFO    MainThread:4200 [wandb_run.py:_config_callback():962] config_cb batch_size 32 None
2021-12-13 20:29:24,344 INFO    MainThread:4200 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-12-13 20:29:24,344 INFO    MainThread:4200 [wandb_run.py:_restore():1758] restore
2021-12-13 20:29:25,324 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 948
  total_bytes: 948
}

2021-12-13 20:29:25,438 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 948
  total_bytes: 948
}

2021-12-13 20:29:25,668 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 948
  total_bytes: 948
}

2021-12-13 20:29:26,676 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 948
  total_bytes: 3207
}

2021-12-13 20:29:26,794 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 948
  total_bytes: 3233
}

2021-12-13 20:29:26,905 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 948
  total_bytes: 3233
}

2021-12-13 20:29:27,012 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3233
  total_bytes: 3233
}

2021-12-13 20:29:27,120 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3233
  total_bytes: 3233
}

2021-12-13 20:29:27,229 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3233
  total_bytes: 3233
}

2021-12-13 20:29:27,338 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3233
  total_bytes: 3233
}

2021-12-13 20:29:27,446 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3233
  total_bytes: 3233
}

2021-12-13 20:29:27,962 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3233
  total_bytes: 3233
}

2021-12-13 20:29:28,445 INFO    MainThread:4200 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3233
  total_bytes: 3233
}
local_info {
}

2021-12-13 20:29:29,509 INFO    MainThread:4200 [wandb_run.py:_append_files():2184] logging synced files
