2022-01-10 18:34:54,722 INFO    MainThread:17832 [wandb_setup.py:_flush():71] setting env: {}
2022-01-10 18:34:54,722 INFO    MainThread:17832 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-10 18:34:54,722 INFO    MainThread:17832 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\Usuario\Desktop\Uni\DataDaniMAPSIV\PSIV\wandb\run-20220110_183454-2kaxz1ju\logs\debug.log
2022-01-10 18:34:54,723 INFO    MainThread:17832 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\Usuario\Desktop\Uni\DataDaniMAPSIV\PSIV\wandb\run-20220110_183454-2kaxz1ju\logs\debug-internal.log
2022-01-10 18:34:54,723 INFO    MainThread:17832 [wandb_init.py:init():404] calling init triggers
2022-01-10 18:34:54,723 INFO    MainThread:17832 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-10 18:34:54,725 INFO    MainThread:17832 [wandb_init.py:init():449] starting backend
2022-01-10 18:34:54,725 INFO    MainThread:17832 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2022-01-10 18:34:54,732 INFO    MainThread:17832 [backend.py:ensure_launched():199] starting backend process...
2022-01-10 18:34:54,911 INFO    MainThread:17832 [backend.py:ensure_launched():204] started backend process with pid: 968
2022-01-10 18:34:54,912 INFO    MainThread:17832 [wandb_init.py:init():458] backend started and connected
2022-01-10 18:34:54,912 INFO    MainThread:17832 [wandb_init.py:init():519] updated telemetry
2022-01-10 18:34:54,958 INFO    MainThread:17832 [wandb_init.py:init():549] communicating current version
2022-01-10 18:34:59,971 WARNING MainThread:17832 [wandb_init.py:init():938] interrupted
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\wandb_init.py", line 917, in init
    run = wi.init()
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\wandb_init.py", line 550, in init
    check = backend.interface.communicate_check_version(
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\interface\interface.py", line 87, in communicate_check_version
    ret = self._communicate_check_version(check_version)
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\interface\interface_queue.py", line 436, in _communicate_check_version
    result = self._communicate(rec)
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\interface\interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\interface\router.py", line 32, in get
    is_set = self._object_ready.wait(timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
